### ISSUE TITLE
Extended the german strings

### ISSUE THREAD

**Issue by Wyqer** [GreuhZbug/greuh_liberation.Altis#103]
Added the missing german strings to the stringtable. (attached as txt, because github don't allow xml files here)
[stringtable.txt](https://github.com/GreuhZbug/greuh_liberation.Altis/files/253411/stringtable.txt)

**Comment by majorwolf** [comment]
why didn't you just make a pull request so he can merge the file lol

**Comment by Wyqer** [comment]
Not that familiar with it, as i thought he only allows some chosen people to transmit pull requests. Think instead of laughing it should be appreciated someone wants to help ;)

**Comment by GreuhZbug** [comment]
Don't worry it's much appreciated ! :)
Thanks for taking the time to do that, I'll merge your pull request in the next version

**Comment by Tschingta** [comment]
Danke sehr! Werds gleich mal ausprobieren.

**Comment by GreuhZbug** [comment]
And merged
