### ISSUE TITLE
Wrong variable name "opfor_troup_transports"

### ISSUE THREAD

**Issue by serialtasted** [GreuhZbug/greuh_liberation.Altis#107]
Instead of being _"opfor_troup_transports"_, you have _"buildinopfor_troup_transportsgs "_. This way if you want to overwrite the troup transport list it doesn't work.

https://github.com/GreuhZbug/greuh_liberation.Altis/blob/4314de09ce2d0d45972a103978063203f0996b38/scripts/shared/classnames.sqf#L324

**Comment by GreuhZbug** [comment]
Failed copy/paste, thanks for noticing, corrected in v0.924
