### ISSUE TITLE
No markers in Apex update

### ISSUE THREAD

**Issue by rlex** [GreuhZbug/greuh_liberation.Altis#108]
Hello
...at least in RC / Preview.
Map is absolutely clean - no FOBs, no capture points, etc.

**Comment by GreuhZbug** [comment]
Apparently this is an Arma 3 bug ?
See: https://www.google.fr/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=arma%203%20apex%20markers

**Comment by rlex** [comment]
It's not exactly clear what causes all markers to disappear. 
Given markers system received a huge rework, i wouldn't be surprised if BIS changed some syntax or something.
I still can't get confirmation from BIS if this is bug or intended change.

**Comment by rlex** [comment]
Fixed in recent RC

**Comment by GreuhZbug** [comment]
Good
