### ISSUE TITLE
Use built in revive

### ISSUE THREAD

**Issue by psykzz** [GreuhZbug/greuh_liberation.Altis#117]
Hey not sure if it has been mentioned but it might be worth looking into the arma revive system to reduce deps on another system.

**Comment by Wyqer** [comment]
**Insert** this in your Description.ext in the missionfile:
`ReviveMode = 1;                         //0: disabled, 1: enabled, 2: controlled by player attributes`
`ReviveUnconsciousStateMode = 0;         //0: basic, 1: advanced, 2: realistic`
`ReviveRequiredTrait = 0;                //0: none, 1: medic trait is required`
`ReviveRequiredItems = 2;                //0: none, 1: medkit, 2: medkit or first aid kit`
`ReviveRequiredItemsFakConsumed = 1;     //0: first aid kit is not consumed upon revive, 1: first aid kit is consumed`
`ReviveDelay = 6;                        //time needed to revive someone (in secs)`
`ReviveMedicSpeedMultiplier = 2;         //speed multiplier for revive performed by medic`
`ReviveForceRespawnDelay = 3;            //time needed to perform force respawn (in secs)`
`ReviveBleedOutDelay = 120;              //unconscious state duration (in secs)`

**Remove** the following in the init.sqf:
`if ( GRLIB_revive > 0 ) then {
	[] execVM "FAR_revive\FAR_revive_init.sqf";
};`

Change the above Revive Settings to your liking and you've the new ArmA 3 Revive System.
But I would recommend to use ACE btw :)

**Comment by BryanBoru** [comment]
+1 on ACE3. all day.
