### ISSUE TITLE
Ammo Box Recycling Issue

### ISSUE THREAD

**Issue by eeriestwalnut55** [GreuhZbug/greuh_liberation.Altis#119]
Not sure if it is a bug with a script or my addition of RHS, however I am having an issue in the lastest release with recycling ammo boxes captured from an enemy FOB. When I try to recycle them after unloading them at my FOB it displays scalar NaN for all values and does not allow me to click the recycle button, thus I can get no ammo income. I have done lots of digging and cannot find a cause, I have also tried using the vanilla ammo boxes with the same result. Please help.

**Comment by Wyqer** [comment]
Does this also happen with a fresh missionfile from here?
It would be best, if you provide the code which you've changed in your missionfile, als you say you've made additions for RHS.

**Comment by eeriestwalnut55** [comment]
I will test fresh from here, I was actually in the process of doing that when i had to leave, so i figured I will post and see if someone had already run into this issue. If not I will post my edits for RHS. All I have changed is the classnames_extension.sqf. I will also upload that in a moment or two.

**Comment by eeriestwalnut55** [comment]
Update:

After testing the raw data from here i found that ammo boxes were working as they were supposed to. 

Here is my classnames_extension.sqf I have edited, this is the only file I have altered
http://pastebin.com/2uXAJcEX

I am not sure where I have made the mistake.

**Comment by Wyqer** [comment]
`ammobox_b_typename = nil;               // Default "Box_NATO_AmmoVeh_F";`
`ammobox_o_typename = nil;               // Default "Box_East_AmmoVeh_F";`
`opfor_ammobox_transport = "rhs_gaz66o_msv";         // Default "O_Truck_03_transport_F";`

You can't recycle an Ammo Box, because you set the Classnames for the ammo boxes to nil.
So the script don't know which kind of ammobox it should attach the recycle Option.
I would recomment you insert the default values,

`ammobox_b_typename = "Box_NATO_AmmoVeh_F";`
`ammobox_o_typename = "Box_East_AmmoVeh_F";`

**Comment by eeriestwalnut55** [comment]
Okay, that makes sense, I thought setting it to nil used the default value. I will fix this, thank you for your assistance!

**Comment by eeriestwalnut55** [comment]
So I thought that this would be a simple fix but it would appear something else is messing with the ammo box recycling. I have replaced the nil with my own custom values and still had the Scalar NaN issue. I used default values and had the Scalar NaN issue. My last attempt was to use a fresh copy off this github and place my classname extensions.sqf over top of it so that i know no other files were edited and I am still having the issue. 

Here is my most recent classname extensions.sqf file

http://pastebin.com/acHaQMSu

I am sure it is something simple that I am missing but I cannot for the life of me figure it out. I appreciate the assistance. Thank you.

**Comment by Wyqer** [comment]
First thought from my side:

You have again 2 nils in your extension. Just set the default values there:
`FOB_typename = "Land_Cargo_HQ_V1_F";`
`FOB_box_typename = "B_Slingload_01_Cargo_F";`

**Comment by eeriestwalnut55** [comment]
So this also did not work, however in comparison to the classnames_extension.sqf that is provided from this git, the values of support stuff in the default one are all nil, leading me to believe that a nil value at the top is not causing this error, i am attempting to compare elsewhere in this sqf to see if I miss anything, do you know of anything else that could cause an error like this?

My other thought is since the modded sqf overwrites vehicles instead of replacing them there could be an issue inside of that part ... I will test that.

Edit: So I have discovered 2 things. If I do not use overwrite = true and use do use the default ammo crates it works fine. If I use any other object as an ammo crate and keep overwrite = false it does not work. If i use default ammo crate and overwrite = true it does not work. I am currently going through each overwrite = true one by one to see what is causing the problem. Do I need an ammo crate under another section to get it to work?

**Comment by eeriestwalnut55** [comment]
Okay, I have solved the issue

When using the classnames_extension.sqf under the support vehicles overwrite, if you want to overwrite support vehicles you MUST include the ammobox class names in this section and set a value for them. It will NOT read the default values. I  suggest to the editing team that in their comment they mention the ammoboxes as a required field as well. See below for example

support_vehicles_overwrite = true;		// If you're going to overwrite this, make sure you have at least Arsenal_typename, Respawn_truck_typename, FOB_box_typename and FOB_truck_typename in there **_(Please add ammobox_b_typename and ammobox_o_typename to this section.)_**
support_vehicles_extension = [
	[Arsenal_typename,10,0,0],
	[Respawn_truck_typename,20,0,5],
	[FOB_box_typename,30,50,0],
	[FOB_truck_typename,30,50,5],
	["Box_NATO_AmmoVeh_F",0,100,0],
	["Box_East_AmmoVeh_F",0,100,0],
