### ISSUE TITLE
 enemies inside the houses

### ISSUE THREAD

**Issue by k4s0** [GreuhZbug/greuh_liberation.Altis#120]
hello, I just wanted to bring to light a fact that I noticed about this mission, when a team approaching a city from a distance the "AI" raise and lower the weapon, remaining motionless, there is a way to avoid this thing ?
sorry for my bad English, i'm waiting for your answer, thank you.

**Comment by Tschingta** [comment]
This should be a bug with CBA https://github.com/CBATeam/CBA_A3/issues/551
I am not sure how to work around or fix it.

**Comment by ShizCalev** [comment]
can be closed.
