### ISSUE TITLE
Virtual Arsenal Classes, Blacklisting, Whitelisting

### ISSUE THREAD

**Issue by Matoshx** [GreuhZbug/greuh_liberation.Altis#22]
Would be possible for you to add next:
- restrict gear arrays by roles (mg, at/aa, sniper, sq/tl/com, marksman)
- blacklist certain gear array so it won't appear in VA

It's a nightmare to see machinegunner-thermaloptic-antitank-medic-ghillie players running around. :)

**Comment by GreuhZbug** [comment]
This becomes a very complicated issue as soon as you factor mods in. Either you have the BIS arsenal and it's unrestricted, or you have a class system with predefined loadouts. That would work on public vanilla servers, so if you agree with that I'd make it a mission option.

As for the blacklisting I need to dig more into the issue, I can't say if it's possible or not at the moment.

Cheers

**Comment by Matoshx** [comment]
By class system with predefined loadouts, would mean that on spawn you have to choose a class/role in order to spawn in? What about ammoboxes, would they be restricted too? Can you explain more how is your class sytem going to work?

Here is a BI Forums topic regarding VA restricting, maybe it could give you an idea or something.

https://forums.bistudio.com/topic/182817-how-to-limit-weapons-in-the-arsenal-of-a-box/

**Comment by GreuhZbug** [comment]
Haha I've read that topic quite a lot today, however it's about the arsenal being linked to ammoboxes, not out of thin air like in liberation. However I've found another way to blacklist items and proceeded to ban deployable weapon backpacks (these weapons shall be purchased instead).

For the class system it means that instead of having the full arsenal you'd get a list of predefined and rigid loadouts to choose from. That would obviously ban all infantry weapon mods from the mission.

There's no way to dynamically restrict the arsenal, and even if there was one, it wouldn't be practical to define a set of rules like "if sniper -> no launchers" as any mod would be able to go around such limitations. So it's either "free" mode or "rigid" mode.

**Comment by Matoshx** [comment]
I had my own way (not fully tested) to restrict VA gear by roles in one of the missions but it has to be applied to the ammo boxes, Liberation VA addAction kind of breaks it.

Ammo box object name = vacrate

initPlayerLocal.sqf:
_null = [] execVM "scripts\VA\arsenal.sqf";

arsenal.sqf:
if (player isKindOf "rhsusf_army_ocp_autorifleman") then {
null = [vacrate] execVM "scripts\VA\VAar.sqf";
};

if (player isKindOf "rhsusf_army_ocp_medic") then {
null = [vacrate] execVM "scripts\VA\VAmed.sqf";
};

VAar.sqf:
_crate = _this select 0;
["AmmoboxInit",[_crate,false,{true}]] spawn BIS_fnc_arsenal;

_availableWeapons = [
"Classname","Classname1","Classname2"
];

_availableMags = [
"Classname","Classname1","Classname2"
];

_availableItems = [
"Classname","Classname1","Classname2"
];

_availableBackpacks = [
"Classname","Classname1","Classname2"
];

//Populate with predefined items and whatever is already in the crate
[_crate,(weaponCargo _crate) + _availableWeapons] call BIS_fnc_addVirtualWeaponCargo;
[_crate,(magazineCargo _crate) + _availableMags] call BIS_fnc_addVirtualMagazineCargo;
[_crate,(itemCargo _crate) + _availableItems] call BIS_fnc_addVirtualItemCargo;
[_crate,(backpackCargo _crate) + _availableBackpacks] call BIS_fnc_addVirtualBackpackCargo;

As I said this only applies to the ammo boxes. Don't know how is this efficient performance wise since I'm not coder/scripter.

**Comment by Matoshx** [comment]
I see what you did there with blacklisting. I'm guessing it's for backpacks only? 
If you are not planning in close future to improve VA restrictions, blacklisting functions for all types of weapons/gear/equipment (not only backpacks) would be highly appreciated.

**Comment by GreuhZbug** [comment]
Sadly blacklisting other types of entries and especially weapons results in massive performance issues and loading bugs on the arsenal, which could be seen in the 908 pre-release.

**Comment by Matoshx** [comment]
How about other way around, whitelisting? Will this also have performance issues? 
Whitelisting does break, in a way, automatic weapon mod detection and fill up, and person has to manually add vanilla or addon weapons/gear/equipment to the mission, but at least Arsenal is not going be filled up with unnecessary stuff.

https://forums.bistudio.com/topic/172792-bis-fnc-arsenal-how-to-whitelist-classes/

**Comment by GreuhZbug** [comment]
As you said whitelisting would prevent people from using mods so it's a no-go, I'd much rather have an optional class system. My own team would hate me if I implemented a limited arsenal.

**Comment by GreuhZbug** [comment]
The class system is noted and will appear in a further release : https://trello.com/c/wMAyNli3/138-class-system
I'll close the issue

**Comment by Matoshx** [comment]
Would be possible to at least add optional code or empty arrays for whitelisting?
