### ISSUE TITLE
Random Patrols

### ISSUE THREAD

**Issue by Matoshx** [GreuhZbug/greuh_liberation.Altis#26]
Does Liberation have random patrols on the island? If not, would be possible for you to add them?
Jumping from objective to objective, especially with one unarmed vehicle, can be rather easy. Unless you make contact with random enemy patrol then that, jumping process, can be slowed down or eliminated. 

They don't have to be infantry only. Sometimes patrols should spawn in with light vehicle only or medium armed vehicle only, but nothing to serious.

Also the parameters for random patrols would be appreciated too. Like enable or disable random patrols, distance they spawn from the players, difficulty or size of the random patrols, etc...

**Comment by GreuhZbug** [comment]
There is already infantry and vehicle patrols between towns. Their density depends on the alert level. They're also the reinforcements that come to defend sectors.
