### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by PHENIXWORKS** [GreuhZbug/greuh_liberation.Altis#27]
![2015-10-07_00001](https://cloud.githubusercontent.com/assets/15023811/10355040/36648498-6d67-11e5-8cf6-b83756cef6c1.jpg)
Bonjour , je ne c' est pas si sa fait parti du jeux ou c' est un bug ?? quand on a libèrè un village le cercle devient bleu mais le petit carré RESTE ROUGE

VER 90.5

**Comment by GreuhZbug** [comment]
C'est un bug, j'aurais besoin des logs RPT du serveur pour voir  ce qui se passe

**Comment by PHENIXWORKS** [comment]
C'est  un serveur privé  : clan hierbabuena    

Date: Thu, 8 Oct 2015 09:57:22 -0700

**Comment by GreuhZbug** [comment]
ça n'aide pas :D
