### ISSUE TITLE
Error in expression

### ISSUE THREAD

**Issue by jus61** [GreuhZbug/greuh_liberation.Altis#28]
Error in expression <

_base_tick_period = _base_tick_period / GRLIB_resources_multiplier;

if ( _bas>
17:47:01   Error position: </ GRLIB_resources_multiplier;

if ( _bas>
17:47:01   Error Zero divisor

**Comment by GreuhZbug** [comment]
Please provide more information as detailed here:

http://greuh-liberation.wikia.com/wiki/How_to_report_a_bug
