### ISSUE TITLE
Halo jump creates duplicate backpacks

### ISSUE THREAD

**Issue by bramjam** [GreuhZbug/greuh_liberation.Altis#32]
Small one.
when people halo jump there are backpacks 'left behind' .  they are duplicates it seems
it's not very clean. would be nice if they are cleaned up.

(got this from DOBGB server)

Version: 0,909a

No server logs yet. (ill try to reproduce the issue on another server. Dogb does not capture server logs)

![2015-10-17_00001](https://cloud.githubusercontent.com/assets/289940/10557765/394c45f2-74b9-11e5-931e-e9f577e47233.jpg)

**Comment by GreuhZbug** [comment]
Noted on trello

**Comment by GreuhZbug** [comment]
Corrected
