### ISSUE TITLE
Uncapturable area after attack battlegroup

### ISSUE THREAD

**Issue by bramjam** [GreuhZbug/greuh_liberation.Altis#35]
Hi zbug, 
on tmg server we had an occurrence of the infamous 'incapturable' area bug. 
Version 0,909a

![2015-10-19_00001](https://cloud.githubusercontent.com/assets/289940/10589869/01c93ada-76ae-11e5-93c6-4b661f4d6c3b.jpg)
![2015-10-19_00002](https://cloud.githubusercontent.com/assets/289940/10589870/01cd1d30-76ae-11e5-9c32-622ba0002489.jpg)

Server logs. and my client logs :
https://gist.github.com/bramjam/edbb645b1e2d9adbf1b9

WHAT happend; (im doing detailled,  just in case the detail is the key)
- we just captured an area. with 1 prisoner.
- a **battlegroup** spawned. shortly after
- we  went back to base.
- we get message selakano airfield is under attack.
- we stand chatting at fob main airfield.
- we decided to **go defend** selekano airfield. we fly in and are there when the counter is down to 4 minutes. (we landed around 1km away on the west mounten.)
- we destroy 4 vehicles. a couple of infintry left. but then we get the message 'you lost selekano airfield'.
- couple of our human guys go on foot toward airfield. shoot the last guys.  (i was still on the hill)
- area not captured... see screenshot.

i hope this helps in narrowing the search for this illusive thingy

**Comment by GreuhZbug** [comment]
It does :D

**Comment by TMG-Maeglinn** [comment]
good to hear! if you require any other server logs or files let me know!

**Comment by GreuhZbug** [comment]
Thanks to the logs I've identified the script that gets stuck. I've put a tentative fix in v0.911, plus more traces in the script in case it doesn't work.
