### ISSUE TITLE
BIS Dynamic Groups

### ISSUE THREAD

**Issue by Matoshx** [GreuhZbug/greuh_liberation.Altis#36]
What do you think about having BIS Group Management in Liberation? Is it any better?

https://community.bistudio.com/wiki/BIS_fnc_dynamicGroups

**Comment by GreuhZbug** [comment]
Might be, I've activated it in the version we're testing, hope it doesn't clash with the current squad management

**Comment by GreuhZbug** [comment]
I've tested it and while the interface is pretty it doesn't bring more functionnality than what we already have. I'd rather improve the current UI or merge it with  the new squad management panel.
