### ISSUE TITLE
HALO Cooldown timer

### ISSUE THREAD

**Issue by Matoshx** [GreuhZbug/greuh_liberation.Altis#41]
Will you add HALO cooldown parameter? Mobile Respawn becomes useless then when you can do HALO jump everywhere at anytime.

**Comment by GreuhZbug** [comment]
Heh, not really. HALO jumping takes some time, people get spread out, if hostiles are close enough you can get killed, you have no solution to go back to base and no solution to change your loadout. On our server we use both depending on the situation and it feels balanced enough.

**Comment by Matoshx** [comment]
I'm saying about having an optional server **PARAMETER** for HALO jump cooldown timer, so players can't do jumps every single time, instead they should wait depending on how long the parameter was set. 
As I said, helicopters, mobile respawns or any other vehicle for transportation becomes useless then, when you have the ability to jump anywhere at **ANYTIME**.

As soon as you get killed by the enemy you jump again and again and again...

You do have the solution to go back to base, by clicking on a ESC respawn button.

**Comment by GreuhZbug** [comment]
Back to your main question
Will you add HALO cooldown parameter? 
-> No
Cheers
