### ISSUE TITLE
Community Upgrade Project - CUP

### ISSUE THREAD

**Issue by jus61** [GreuhZbug/greuh_liberation.Altis#43]
would be pleased if they would integrate this addon

 https://forums.bistudio.com/topic/179326-community-upgrade-project-cup/

**Comment by GreuhZbug** [comment]
You can put as many classnames as you want into classnames.sqf, either do it on your side or provide me with a list of classnames+costs to put in the main version (which will only make a difference for people playing with CUP vehicles)

**Comment by jus61** [comment]
Thank you
