### ISSUE TITLE
Adjust the optics slightly

### ISSUE THREAD

**Issue by jus61** [GreuhZbug/greuh_liberation.Altis#47]
"ColorCorrections" ppEffectEnable true; 
"ColorCorrections" ppEffectAdjust [0.88, 0.88, 0, [0.2, 0.29, 0.4, -0.1], [1, 1, 1, 1.5], [0.25, 0.19, 0.19, 0.0]];
"ColorCorrections" ppEffectCommit 1;

**Comment by GreuhZbug** [comment]
Uh, could you please explain?

**Comment by jus61** [comment]
Explaining is somewhat difficult because my English is very bad xD !
Try it and you'll see what I mean:

Please add the in their init.sqf:
//---------------Custom process Effects ---------------
[] execVM "scripts\effect.sqf";
//---------------Custom process Effects End ---------------

and in the effect.sqf:

//---------------Custom process Effects ---------------
"ColorCorrections" ppEffectEnable true; 
"ColorCorrections" ppEffectAdjust [0.88, 0.88, 0, [0.2, 0.29, 0.4, -0.1], [1, 1, 1, 1.5], [0.25, 0.19, 0.19, 0.0]];
"ColorCorrections" ppEffectCommit 1;
---------------Custom process Effects End ---------------

**Comment by GreuhZbug** [comment]
I still don't see why, and that would conflict with the ppeffects of the revive screen anyways

**Comment by jus61** [comment]
ARMA ORGINAL:
http://i.ytimg.com/vi/_8DpvTt6Q1U/maxresdefault.jpg

Custom process Effects:
http://images.akamai.steamusercontent.com/ugc/403430173627294141/6FE148EC5325DB8E9746082788FEFED4E9C6B796/

http://images.akamai.steamusercontent.com/ugc/403430173627294347/FCF65558E79FB65C545882D06DDAAE84F25ADF6F/

**Comment by GreuhZbug** [comment]
Haaaaaaa yeah no you can have the same functionality with sweetFX. You can make that modification in your version of the mission but every revive screen will erase it
