### ISSUE TITLE
Day/Night  Duration

### ISSUE THREAD

**Issue by jus61** [GreuhZbug/greuh_liberation.Altis#48]
if (!isServer) exitWith {};

while {true} do
{
    if (daytime >= 20 || daytime < 6) then   // after 8pm and before 6am time multiplier changes
    {
        setTimeMultiplier 36      // faster night cycle 
    }
    else
    {
        setTimeMultiplier 16      // faster day cycle 
    };

```
uiSleep 30;
```

};

**Comment by GreuhZbug** [comment]
Noted on trello, will happen in a future release
