### ISSUE TITLE
Unit spawn incorrectly if map is 'without water'

### ISSUE THREAD

**Issue by bramjam** [GreuhZbug/greuh_liberation.Altis#49]
Hi Zbug,

As you know i'm porting liberation to other maps. but i found that on the maps where there is no surrounding water. allot of the ai don't spawn in the circles.
i saw a smoke stack at the bottom left corner of the map and see that the units spawn there before they are moved. problem is that they spawn so fast in the same spot that they 'explode'. (see screenshots)
(but next weird thing is that the ones that survive only 20% actually gets relocated to to the sector)
(0.912. see githubs on my profile. link to logs a the bottem here)

I see that all maps have a Green sphere at the bottom left corner. (also altis.) and based on the [code](https://github.com/GreuhZbug/greuh_liberation.Altis/blob/77ef73674187b2e3e1c2d8c718f1a68e6b72e687/scripts/client/build/do_build.sqf#L119) i assume you create them there and then relocated them. i'l need a different way of spawning them in for non island maps.

From esseker after battle group spawn:
![2015-10-31_00011](https://cloud.githubusercontent.com/assets/289940/10864186/d3455ad6-7fe5-11e5-9dfc-280baa038955.jpg)

Takistan when attacking a radiotower:
![2015-10-31_00004](https://cloud.githubusercontent.com/assets/289940/10864167/4dfbb80c-7fe5-11e5-8fd1-5cdb1ce00ab7.jpg)
Takistan attacking major city
![2015-10-31_00005](https://cloud.githubusercontent.com/assets/289940/10864166/4df99806-7fe5-11e5-9c95-d4354edd1206.jpg)
On Esseker attacking a radio tower
![2015-10-31_00006](https://cloud.githubusercontent.com/assets/289940/10864168/4dfc6928-7fe5-11e5-9b06-0f17fab462ce.jpg)
![2015-10-31_00007](https://cloud.githubusercontent.com/assets/289940/10864169/4dfca794-7fe5-11e5-88ac-e9e318a33bdd.jpg)
![2015-10-31_00008](https://cloud.githubusercontent.com/assets/289940/10864170/4dfd95aa-7fe5-11e5-8de5-70b22739ba56.jpg)
![2015-10-31_00009](https://cloud.githubusercontent.com/assets/289940/10864171/4dfe86a4-7fe5-11e5-9851-46352cf05097.jpg)
tttt
![2015-10-31_00010](https://cloud.githubusercontent.com/assets/289940/10864172/4e10e52e-7fe5-11e5-950c-b0de0766c3e1.jpg)
![2015-10-31_00001](https://cloud.githubusercontent.com/assets/289940/10864174/4e173a28-7fe5-11e5-819f-6dba13961d8a.jpg)
i saw the dot also on Altis
![2015-10-31_00003](https://cloud.githubusercontent.com/assets/289940/10864175/4e17d348-7fe5-11e5-849b-6f01b981fef1.jpg)

Log Files:
https://gist.github.com/bramjam/40ba91ae2f087bb752c3

**Comment by bramjam** [comment]
or make the 'spawn point' configurable/moveable so i can put it in a river/pond :)

**Comment by GreuhZbug** [comment]
Ok I'll fix that
