### ISSUE TITLE
Problem userconfig 

### ISSUE THREAD

**Issue by jus61** [GreuhZbug/greuh_liberation.Altis#50]
I have the problem that the userconfig not recognized ( only in this mission )
8:09:47 Warning Message: Script userconfig\VCOM_AI\AISettingsV2.sqf not found

The AISettingsV2.sqf but in the folder available:
 
http://up.picr.de/23558542lu.png

**Comment by GreuhZbug** [comment]
This is not mission related

**Comment by jus61** [comment]
When I start another mission he recognizes the! Maybe you can help me, I have no idea why this liedt

**Comment by jus61** [comment]
ok found the error!

Add the parameters to their starting: "-filepatching"
