### ISSUE TITLE
HALO action limitation

### ISSUE THREAD

**Issue by Matoshx** [GreuhZbug/greuh_liberation.Altis#53]
Currently, HALO jumps are available from three places: Base Chimera, FOBs and Mobile Respawn. Would you limit it only to the Base Chimera and FOBs? 

Here's an idea. How about having airfields as a requirement for HALO. BLUFOR must have at least one captured airfield to be able to do HALO jumps. If there are no airfields on the BLUFOR side, jumps are not possible then.

**Comment by GreuhZbug** [comment]
- At any mobile respawn you can redeploy to a FOB and then halo jump from there, so it doesn't change much either way.
- There's nothing differenciating airfield sectors from any other factory. That would likely break ports to other maps too. The benefit is small, more likely public server admins are going to complain that their people cant' move around as they please.
- You really dislike halo don't you :p
