### ISSUE TITLE
F_getCommander.sqf Line 5

### ISSUE THREAD

**Issue by jus61** [GreuhZbug/greuh_liberation.Altis#57]
http://images.akamai.steamusercontent.com/ugc/389922904405361731/91A5C01E87AF2366190D27F9C43A5CDD8FA986F5/

**Comment by GreuhZbug** [comment]
This works well with the original classnames.sqf so it's likely you've overwritten that file or didn't merge your modifications in the right way. As a sidenote I don't provide support for modded versions yet, and you should only open issues for problems that can be reproduced in vanilla.
