### ISSUE TITLE
Error position: <_nextvehicle;

### ISSUE THREAD

**Issue by jus61** [GreuhZbug/greuh_liberation.Altis#58]
Error Undefined variable in expression: _nextvehicle
16:51:03 File mpmissions__cur_mp.Altis\scripts\server\game\save_manager.sqf, line 215
16:51:03 Error in expression < _nextbase;
_assigned_vehicles pushback _nextvehicle;
GRLIB_vehicle_to_military_>
16:51:03   Error position: <_nextvehicle;
GRLIB_vehicle_to_military_>

**Comment by GreuhZbug** [comment]
I'd guess that elite_vehicles is not correctly defined due to an issue with your version of classnames.sqf
