### ISSUE TITLE
 Error in expression configFile / 'cfgVehicles' / _classtotes

### ISSUE THREAD

**Issue by jus61** [GreuhZbug/greuh_liberation.Altis#59]
I now have the original Fils:

 Error in expression <
isClass ( configFile / 'cfgVehicles' / _classtotest );>
18:48:04   Error position: <_classtotest );>
18:48:04   Error Undefined variable in expression: _classtotest
18:48:04 File mpmissions__cur_mp.Altis\scripts\shared\functions\F_checkClass.sqf, line 2

**Comment by GreuhZbug** [comment]
Still not providing support for modified versions
