### ISSUE TITLE
MicroDAGR + status position

### ISSUE THREAD

**Issue by rlex** [GreuhZbug/greuh_liberation.Altis#65]
Hello, can you please move status text a bit up?
There is small issue with opened MicroDAGR from ACE:

![arma3client_performance_154_133788_v6 2015-12-21 17-34-27-302](https://cloud.githubusercontent.com/assets/84462/11932847/497df500-a809-11e5-9355-f21670de7a4d.jpg)

**Comment by rlex** [comment]
sorry, screenshot was blank, so i reuploaded it.

**Comment by GreuhZbug** [comment]
There's two frames on top of the right side  UIs (nearest sector and CSAT attack in progress), if I move these up they're going to clip the hints and character information. There's so many mods that making sure everything works with everything is not really possible ;)

This should solve your issue however:
https://trello.com/c/vHuMr2xi/160-choose-ui-screen-position
