### ISSUE TITLE
Only admin can repackage FOB

### ISSUE THREAD

**Issue by rlex** [GreuhZbug/greuh_liberation.Altis#72]
Seems like with permissions system enabled, only logged in admin can repackage FOB.
Will be nice to have separate permission for FOB management.

**Comment by GreuhZbug** [comment]
Admin and commander, actually
FOB repackage is the quickest way to grief and I didn't want to allow everyone to do it on servers that don't use permissions

**Comment by rlex** [comment]
> that don't use permissions

That's the point. I'm asking about permission-enabled server.

**Comment by GreuhZbug** [comment]
If you disable permissions everyone has every permission. If you create a permission for FOB repackage everyone will be able to do it
