### ISSUE TITLE
Static titan units leaving their position

### ISSUE THREAD

**Issue by rlex** [GreuhZbug/greuh_liberation.Altis#75]
...after loading game
1) Spawn static AA turret with crew
2) Place it somewhere 
3) Stop server
4) Load server
5) Unit left his static titan.

This only affects titans, not HMG/GMG

**Comment by GreuhZbug** [comment]
Hmmm this doesn't happen on our server, with a few manned titans defending one of the fobs. Is the ground level, do you find the titan standing upright? In some places it might spawn on a slope and tilt, and I suppose the gunner won't stay in when that happens

**Comment by GreuhZbug** [comment]
Need more information to reproduce

**Comment by rlex** [comment]
Hmph, seems not happening anymore. I must also say that i use ACE which messes with AI and ASR AI as well.

**Comment by GreuhZbug** [comment]
No worries, if you ever come across a 100% reproduction scenario feel free to reopen the issue and let me know
