### ISSUE TITLE
Prisoner leave group when entering vehicle 

### ISSUE THREAD

**Issue by bramjam** [GreuhZbug/greuh_liberation.Altis#76]
seems to be new in 0.919

Faron602: ok bram found a bug, when we tell prisoners to get in truck they get in and then leave the group
Faron602: hi bram the prisoner system must be bugged, you capture he joins group but when you tell them to get into vehicle they get in then instantly leave group

**Comment by GreuhZbug** [comment]
Ha yes, I knew something was odd on the last test. Will correct in the next version

**Comment by GreuhZbug** [comment]
Corrected in 0.920, and prisoner behaviour has been enhanced in some funny ways
