### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by rlex** [GreuhZbug/greuh_liberation.Altis#79]
What will happen if N of elite vehicles is more than number of military bases? 
Thought i might port that to some other map (maybe Cherno and Takistan), but they surely lack amount of military bases.

**Comment by GreuhZbug** [comment]
If i remember my own stuff correctly, if you have 15 bases and 20 elite vehicles, at the beginning of the campaign the game is going to pick 15 vehicles at random, so 5 of the elite vehicles will be unlocked by default. And it will be a new draw for each new campaign.

For smaller maps I had the idea to make a "lightweight" version of the resources system with only credits, so the lack of military bases would matter less. You'd still have all the different types and different defenders behaviours but the resource yielded would always be the same only one.

**Comment by GreuhZbug** [comment]
Closing if you're happy with that?

**Comment by rlex** [comment]
I was going to suggest packing several vehicles into one military base, but seems you handled it already.
Yep, this seems to be OK.
