### ISSUE TITLE
FOB destruction seems to not handled properly

### ISSUE THREAD

**Issue by rlex** [GreuhZbug/greuh_liberation.Altis#80]
Long story short, i messed up with my plane and fired GBU-10 instead of GBU-12, so instead of precisely striking enemy tank near one of our FOBs i destroyed everything near it. Including our FOB. I'm a good pilot...
Well anyway. FOB was still available for redeploy. But there was no FOB, only big crater. As i stood in that crater (where was my precious FOB) i was able to perform usual FOB actions like build, arsenal and etc. I was even able to repackage it and redeploy. Seems like FOB attached to something else than FOB building?

**Comment by GreuhZbug** [comment]
Tying FOBs to the HQ building would allow massive griefing to happen on public servers. Connect, grab c4, profit. I could however make the HQ building invincible so it can only be destroyed when opfor forces capture the fob. That way people would stop wondering about it, I can understand it's confusing as hell

**Comment by rlex** [comment]
Probably FIRED eventhandler can be prevented when FOB is not assaulted.
This will work for grenades but i'm not sure about C4 (especially ACE ones)

**Comment by GreuhZbug** [comment]
Corrected in v0.921
