### ISSUE TITLE
Laser designator batteries

### ISSUE THREAD

**Issue by rlex** [GreuhZbug/greuh_liberation.Altis#81]
Old BIS bug. When you have designator and respawn, you will spawn without batteries.
This is very annoying if you fly plane fully loaded with LGBs, and turns out none of your squadmates have batteries.
Something like this 

```
if player hasWeapon "Laserdesignator" then {
  AddMagazine "Laserbatteries";
};
```

On respawn and take loadout function should probably fix the issue.

**Comment by GreuhZbug** [comment]
Done in 0.921
