### ISSUE TITLE
Save location / How to share save?

### ISSUE THREAD

**Issue by rainx0r** [GreuhZbug/greuh_liberation.Altis#85]
Greetings! Not exactly an "Issue", but rather a question and I'm not quite sure where else to ask it. So my group of friends have been playing Liberation for about the past month, and it's been great and I can not thank the development team enough for making it so good!
However, the friend who always hosted the server (locally, not a dedicated one) has not had much time lately to play, so we were wandering whether he could transfer his save to us.
At first glance, we thought that the save would most likely be here 
`C:\users\<name>\Documents\Arma 3\Saved\mpmissions`, or 
`C:\users\<name>\Documents\Arma 3 - Other Profiles\<profilename>\Saved\mpmissions`
, and indeed if either of the folders existed, there would be another 2 folders inside, "co40_liberation.Altis" as well as "greuh_liberation.Altis", however these folders were empty.
So, since in your Armaholic post you mention 

> Also you should know that the savegame is stored in your Arma profile (along with the BIS arsenal loadouts for example), so removing or wiping your profile will delete your savegame.

So, shouldn't it be saved where I mentioned? If not, where is the actual savegame located?
I should also mention that I'm quite new to Arma 3 so maybe this is really obvious, but not really to me so any help would be really appreciated!

**Comment by GreuhZbug** [comment]
http://greuh-liberation.wikia.com/wiki/Server_Admin
Savegame paragraph
Cheers

**Comment by rainx0r** [comment]
Thanks a lot!
