### ISSUE TITLE
Question on the scripts.

### ISSUE THREAD

**Issue by JasonAlanTerry** [GreuhZbug/greuh_liberation.Altis#90]
@GreuhZbug Hello, so I have been working ALLOT over the past few days with this mission, and have been attempting to reverse engineer it to make use of some more advanced AI spawn scripts.

Is there any way you could make some time to discuss with me how your scripts work, and more importantly why you chose the given methods.

I couldn't find any link to your arma clan, and am unsure if you still play arma.

add my steam @ loneangelic or better yet, join my clans TS and get ahold of me, J. Terry.

66.150.214.230:9998 - TFV

**Comment by GreuhZbug** [comment]
If you have specific questions I may try to answer them, otherwise your request sounds like a huge time investment for no reason at all? I'm not doing anything difficult and you have all the resources online:
https://community.bistudio.com/wiki/Main_Page
https://forums.bistudio.com/forum/154-arma-3-mission-editing-scripting/

**Comment by JasonAlanTerry** [comment]
Interestingly enough, I didn't realize you where an asshole until just now. So thanks. A simple no would have been fine.

**Comment by GreuhZbug** [comment]
That surely is an interesting way to react when someone doesn't give you what you want right away. I assumed we were among adults but obviously I was mistaken.

I'd rather spend time working on the mission and make things that everyone will enjoy, than spend time answering questions that already have their answers in the links I've given you. Does that make me an asshole? Maybe...

I assumed you were perfectly capable of solving problems on your own, using the same resources I've been using to learn about scripting, and I thought you'd get more out of the experience if you learned by yourself than having someone else do most of the job for you. Does that make me an asshole? Maybe...

As you guessed I've stopped playing Arma, yet I'm still working a least a little on this mission even though it has stopped being any fun a while ago. I don't owe you anything, not to you, not to anyone else. It's insane to think I'd be spending my time to fix your problems for free. I don't know what kind of fantasy world you live in but in the real world that just doesn't exist.

**Comment by JasonAlanTerry** [comment]
The above is why I shouldn't drink and use the internet, have a good day. Sorry....Just a bad timing for me to respond, and your right, I can do this on my own, I just need to not be a lazy fuck about it...
