### ISSUE TITLE
EDEN 3D editor

### ISSUE THREAD

**Issue by AlexTriada** [GreuhZbug/greuh_liberation.Altis#91]
Convert please to 3D version!
I have tried - i have errors with the zeus

**Comment by GreuhZbug** [comment]
Last time I checked the 3D editor couldn't handle virtual clients such as Zeus, spectators and headless clients, making the mission unplayable, so I'm sticking to the 2D editor until a patch comes around. And anyways with liberation I don't really see the need to use the 3D editor ?

**Comment by AlexTriada** [comment]
2D editor will be cut from arma 3, at least so

**Comment by GreuhZbug** [comment]
When that happens I'll look into it

**Comment by AlexTriada** [comment]
(( not cool

**Comment by GreuhZbug** [comment]
You didn't provide any argument as to why you'd need to use the 3D editor with liberation? Not cool either

**Comment by AlexTriada** [comment]
2D editor will be cut from arma 3, at least so -"You didn't provide any argument"

**Comment by AlexTriada** [comment]
-not cool twice
