### ISSUE TITLE
RHS: Vehicles

### ISSUE THREAD

**Issue by TheLt** [GreuhZbug/greuh_liberation.Altis#94]
Hello. I am a member of a gaming community that plays a lot of Liberation. We are Currently running both the Russian and US RHS packs and we would like to add more of the vehicles from the mod pack into the in game builds menu. I'd really appreciate any guidance that you could provide in this endeavor. Thanks a ton
TheLt.

**Comment by GreuhZbug** [comment]
You will need to edit the mission and modify classnames_extension.sqf to add what you need. You can either unpack the pbo file or retrieve the scenario files from here. You can also find a bunch of RHS ports and more info on how to do it here:
https://forums.bistudio.com/topic/183734-mpcti-coop-liberation-beta/

**Comment by TheLt** [comment]
thanks a ton! I really appreciate the help.
