### ISSUE TITLE
Errors found on search_and_rescue.sqf

### ISSUE THREAD

**Issue by serialtasted** [GreuhZbug/greuh_liberation.Altis#96]
Line 20: _helowreck (setDir random 360);
should be:_helowreck setDir (random 360);

Line 28 and 30 you have a ; after BIS_fnc_relPos. Shouldn't be there.

**Comment by GreuhZbug** [comment]
I know what you did there :p That script isn't finished and never executed yet, just disregard ;)

**Comment by serialtasted** [comment]
ahahaha yeah.. couldn't resist
