### ISSUE TITLE
9.23 IA not spawning

### ISSUE THREAD

**Issue by cpt-fred** [GreuhZbug/greuh_liberation.Altis#98]
Hello, past Saturday after some minutes of playing on 9.23, the enemys IA did not spawn in towns.

Else our server was not overloaded and and IA limit was not reached, we have 2 headless clients with 47fps permanently and the server to.

After capturing two points, the enemy IA started to respawn, so this problem is random

**Comment by GreuhZbug** [comment]
Could you please upload your server logs and headless client logs so I can look into it? (rpt files)
Thanks

**Comment by cpt-fred** [comment]
Salut!

Here you can download the zipped rpt https://goo.gl/4TwKX8

The mission 0.923 was loaded at first and changed to 0.922 before 00h53mn

**Comment by cpt-fred** [comment]
Since last satuday the problem did not reproduced. 

Exept once when players and AIs were on a town and no red circle on map or enemys on horizon.
