### ISSUE TITLE
AI recruitment limit for players parameter

### ISSUE THREAD

**Issue by Matoshx** [GreuhZbug/greuh_liberation.Altis#99]
It seems that players are allowed to recruit many AIs into their squads. Could you somehow limit that, so that they can't recruit them anymore after they reach the limit defined by the mission parameter?

**Comment by GreuhZbug** [comment]
Will add a mission parameter

**Comment by cpt-fred** [comment]
Actually the limit is 10 by player. 

But you if you are the commander, by zeus menu you can add more than 10 IA per player

**Comment by GreuhZbug** [comment]
Yep, but I won't be able to prevent whatever Zeus is able to do. That's why I hate external dependencies.

**Comment by cpt-fred** [comment]
You right!

**Comment by GreuhZbug** [comment]
Added mission param, default value 10
